Cargo.toml, src/android.rs, src/build.rs, src/lib.rs
this was the minimal changes to get it running on Windows (only working with `pc-windows-msvc` Rust due to dependencies of the `cargo` crate)
have tested that it still compiles on a mac but the one i have isn't setup for android or ios dev so haven't been able to test that
=> Windows build

src/android.rs
when connected over tcpip the name is an ipaddress and port 192.168.1.104:5555 for example. This doesn't get picked up by the current regex
=> accept any android device name that isn't whitespace

src/android.rs, src/linker.rs
i wanted to run aarch64 tests on my phone, and x86 tests on the emulator so i fixed this 👍  have tested it on windows and macos
- detect and accept targets that are valid for the device
- prefer arm-linux-androideabi if valid (because it's tier1)
- fix copying of sources and test data to device
- general tidying in android.rs / linker.rs
- you can override api level with `$ANDROID_API`
=> support more android architechtures

Cargo.toml, README.md, src/android.rs, src/config.rs, src/errors.rs, src/ios/xcode.rs, src/lib.rs, test-ws/test-app/.dinghy.toml
Allows files in .gitignore to be copied as test data.
See #24
=> Allow copy_git_ignored to be added to test data

src/config.rs, src/ssh.rs
Some fixes and improvements for ssh mode:
- Implement clean_app
- Allow port to be overridden #26 
- Allow path to be overridden
=> Implement clean_app in ssh, add path and port options

Cargo.lock, Cargo.toml, src/bin/cargo-dinghy.rs, src/errors.rs
Bumped following dependencies:
- `cargo` => `0.21.x`
- `error-chain` => `0.11.x`
- `clap` => `2.26.x`
=> Bump dependencies

dinghy-lib/src/compiler.rs
Currently, in the Android NDK r19b, there are multiple versions of the same library for different architectures. Dinghy would find the correct lib file first, but then would search for more lib files and find the files for incorrect architectures. It led to some strange behaviors where Dinghy would try to run a 64 bit ARM binary with a 32 bit Intel dynamic library.
This fix applies a filter on the library file path list by taking the first occurrence of a library file and discard the rest of the occurrences. Therefore, there is only one version of each lib in the list, most likely the fitting one.
=> Fix multiple versions of the same dynamic lib used

cargo-dinghy/src/main.rs, dinghy-lib/src/android/mod.rs
Previously, the `auto-android-[ARCHITECTURE]` platform was building for the latest API level (28).
Now, there are more platforms available : one platform per API level available. Each android auto platform are now using the following naming convention : `auto-android-[ARCHITECTURE]-api[API_LEVEL]`.
The `all-platforms` subcommand output was modified to output the available platforms in alphabetical order for aesthetic purposes.
=> Android ndk 19+ API level choice

cargo-dinghy/src/main.rs
Previously, running the `-d` argument for an android device without explicitly defining the platform would randomly take a platform with the fitting architecture but with a certain API level which was a semi-random choice of all available API levels.
Now, the choice will be to take the default API level of the device architecture, which is currently pointing to API level 21 for all architectures. The user can still specify a particular API using the `--platform` argument which works with `-d`.
=> Make automatic platform decision for a given device deterministic

.travis.sh, .travis.yml, dinghy-lib/src/errors.rs, dinghy-lib/src/ios/device.rs, dinghy-lib/src/ios/xcode.rs, docs/ios.md
Given that https://bugs.llvm.org/show_bug.cgi?id=36580 seems to be a bug in lldb, I figure it's worth having a work around using `xcrun simctl launch`
I've spent a bunch of time trying to get the exit status of the app to actually propagate but I'm not sure 
how to make `simctl` do it. I don't have a machine with Xcode 8 to see if it propagated before but, I think it's a step forward to just have the test outputs running and being displayed.
Sample output:
```
$ cargo dinghy --platform auto-ios-x86_64 test
INFO  cargo_dinghy > Targeting platform 'auto-ios-x86_64' and device '078869FD-7B1E-4BB2-AE23-8FBDDF952715'
Finished dev [unoptimized + debuginfo] target(s) in 0.03s
Dinghy: 19151
running 4 tests
test tests::pass::it_works ... ok
test tests::fails::it_fails ... FAILED
test …
```
=> Change IosSimDevice to use xcrun simctl launch rather than lldb

Cargo.lock, dinghy-build/Cargo.toml, dinghy-build/src/bindgen_macros.rs, dinghy-build/src/lib.rs
- Remove the bindgen dependency on dinghy-build.
- Move every bindgen related code to macros to make dinghy-build independent from bindgen library.
- Add a fix for bindgen versions >= 0.49 related to a cross-compilation behavior change in bindgen.
=> Refactor bindgen related code 

Cargo.lock
there is a regression in the latest version of the crate url version 2.1.1
the following code when invoked with an url whose scheme is `ssh` will return an error:
```url.set_scheme("https").unwrap();```
ref : https://github.com/rust-lang/cargo/blob/0.41.0/src/cargo/util/canonical_url.rs#L42
here is a simple test case to reproduce the issue :
```
extern crate url;
use url::Url;
fn main() {
let mut url = Url::parse("ssh://example.net").unwrap();
let result = url.set_scheme("https");
assert_eq!(url.as_str(), "https://example.net/");
assert!(result.is_ok());
}
```
it will work with :
```
cargo update --package url --precise 2.0.0
```
it will fail with:
```
cargo update --package url --precise 2.1.1
```
ref : https://github.com/servo/rust-url/blob/v2.1.1/src/lib.rs#L1987
=> use crate url 2.0.0

Cargo.lock, dinghy-lib/Cargo.toml
A regression in the `url` patch 2.1.1 caused the `cargo` lib in dinghy to panic when compiling crates with git ssh dependencies. This is described in servo/rust-url#577. [A workaround](https://github.com/rust-lang/cargo/pull/7787) has been merged in cargo 0.43, but the version is not yet released. On the meantime, dinghy should use the url version 2.1.0.
Fix #101
=> Revert `url` lib bump to 2.1.0

dinghy-lib/src/device.rs
https://developer.android.com/ndk/guides/cpp-support
=> libc++_shared.so must be included for android deployment 

dinghy-lib/src/config.rs, dinghy-lib/src/ssh/device.rs
on some ssh devices `rsync` is not necessarily installed.
this allow the upload of a pre-build `rsync` binary on the target ssh device, useful if `/usr/bin/rsync` does not exists on the target, this is done by adding `install_adhoc_rsync_local_path` in the `dinghy.toml`:
```
[platforms.rsync-test]
rustc_triple='aarch64-unknown-linux-gnu'
toolchain='/home/treym//toolchains/rsync-test/aarch64-unknown-linux-gnu'
[ssh_devices]
ci-rsync-test-001 = { hostname = "192.168.1.34", username="test", platform="rsync-test", install_adhoc_rsync_local_path="/home/treym/toolchains/rsync-test/prebuilt/bin/rsync" }
```
=> add upload rsync binary step for the ssh devices

docs/android.md
Add a new chapter in the documentation to explain how to use the new Android NDK.
=> Android ndk 19+ documentation

dinghy-build/src/bindgen_macros.rs
create the correct builder for target that does not have a sysroot
=> Fix targets which does not have sysroot

dinghy-lib/src/ssh/device.rs
This can be quite handy for example in order to test that test resources
are properly copied by running it directly on localhost /
troubleshooting the remote test exec on a faster machine
Sample configuration in dinghy.toml
```toml
[ssh_devices]
hostssh = { hostname = "localhost", username="chucknorris" }
```
and then
```bash
$ cargo dinghy -d hostssh test
```
=> Allow SSH devices to use the host toolchain

Cargo.lock, dinghy-lib/Cargo.toml, dinghy-lib/src/compiler.rs, dinghy-lib/src/config.rs, dinghy-lib/src/host/device.rs, dinghy-lib/src/ssh/device.rs
Add shell expansion to run command arguments. For instance, in dinghy.toml:
```
[ssh_devices]
raspi = { hostname = "raspi-kali.local", username="pi", platform="raspbian-stretch", remote_shell_vars= { HOME="/home/pi/" } }
raspi3u64 = { hostname = "raspi-kali-home-u64.local", username="ubuntu", platform="aarch64-unknown-linux-gnu", remote_shell_vars= { HOME="/home/ubuntu/" } }
```
then I can get ~ (and ENVIRONMENT_VARIABLES) expanded using the proficed config (or the local envir if targetting HOST). This allow to manage some heavy test resources by hand instead of using dinghy synchro.
```
cargo-dinghy -v -d pi3u64 run --release --no-default-features --features onnx -- "~/.cache/en_libri_real/model.onnx" -i Sx40xf32 --output-node output --pulse 24 -O -vvv dump --cost --profile
```
Note that …
=> experimental shell expansion in run

dinghy-lib/src/ios/device.rs, dinghy-lib/src/ios/helpers.py, dinghy-lib/src/ssh/device.rs
This is quite hacky; but it enables the metal debug layer (by default). This same code could be used to add other environment variables.
Probably shouldn't be merged as-is.
=> iOS environment variable support

dinghy-lib/src/android/mod.rs
=> Log on Android NDK not found

Cargo.lock, dinghy-lib/Cargo.toml, dinghy-lib/src/android/mod.rs
Check Android NDK in non legacy path (`$ANDROID_SDK_ROOT/ndk/$NDK_VERSION`).
If there are multiple versions of NDK installed, the latest version following semver rule will be selected.
Dependencies:
Add semver for parse and comparing NDK versions.
Add tempfile in dev for testing.
I'm using Cargo 1.46.0 (149022b1d 2020-07-17). I think they changed the `Cargo.lock` format.
=> Check Android NDK in non legacy path

dinghy-lib/src/compiler.rs
=> Prevent deployment of libdl.so on Android

dinghy-lib/src/ssh/device.rs
On a system with rsync not installed the error message is a simple
`FilenotFound` witch is a bit hard to debug
=> Better error message on rsync exec

dinghy-lib/src/compiler.rs, test-ws/Cargo.lock, test-ws/Cargo.toml, test-ws/test-proc-macro/Cargo.toml
Tests for these are built by `cargo` for the host platform, and hence don't make sense to run in `cargo dinghy` (and will fail horribly if we try).
=> Dont run tests for `proc-macro` crates

dinghy-lib/src/compiler.rs
Follow-up for #144, ping @madsmtm .
So, the CI was not made to run on PRs (for ages, since migration from travis).
This prevented us from noticing a nasty side-effect that was actually detected by CI. Then when main failed, I guessed wrongly it was an external cause, like the rust bump a few days before, so did not rush for a fix... Anyway the CI script is running now.
WDYT ?
=> tests are actually runnable on host platform

dinghy-lib/src/ios/device.rs
This changes the `options` dictionary, though I couldn't verify that it made a difference
=> Fix "Developer" typo

dinghy-lib/src/ios/device.rs
This was originally found in 56644228b77686f9da82be30d0846bbf8dc354c3, I've just uncommented it because it made my setup work:
- Device: iPad mini 1st generation, running iOS 9.3.6
- Host: macOS 10.14.6 Mojave
=> Fix iOS 9.3

dinghy-lib/src/ios/device.rs
I went to write some iOS unit tests today and found that the output for `lldb -s <script>` has removed blank lines in the output.
It used to be something like:
```
(lldb) command source -s 0 '../lldb-script'
Executing commands in '/Users/simlay/projects/rust-ios/dinghy/lldb-script'.
(lldb) attach 9325
Process 9325 stopped
* thread #1, stop reason = signal SIGSTOP
frame #0: 0x0000000202f4a455 dyld`invocation function for block in dyld3::MachOFile::forEachSegment(void (dyld3::MachOFile::SegmentInfo const&, bool&) block_pointer) const + 549
dyld`invocation function for block in dyld3::MachOFile::forEachSegment(void (dyld3::MachOFile::SegmentInfo const&, bool&) block_pointer) const:
->  0x202f4a455 <+549>: callq  *0x10(%rdi)
0x202f4a458 <+552>: movq   0x28(%r14), %rax
0x202f4a45c <+556>: movq …
```
=> Fix iOS simulator tests with lldb 13

dinghy-lib/src/ios/xcode.rs
This is the same fix from https://github.com/burtonageo/cargo-bundle/pull/108 to fix https://github.com/burtonageo/cargo-bundle/issues/91.
=> Fix iOS bundle to make app use the full screen

dinghy-lib/src/ios/device.rs, dinghy-lib/src/ios/mod.rs, dinghy-lib/src/ios/platform.rs
Closes #147.
I don't think we can test this in CI. I've tested it on my m1 and it works as expected.
This change results in `cargo dinghy all-devices` shows:
```
$ cargo dinghy all-devices
List of available devices for all platforms:
Host: [host]
IosSimDevice { "id": "09EA58D0-0385-4151-AEFB-EBD5D40BA04B", "name": iPhone 8, "os": com.apple.CoreSimulator.SimRuntime.iOS-15-4 }: [auto-ios-aarch64-sim, auto-ios-x86_64]
IosSimDevice { "id": "DF2E630F-5872-4718-9F1C-B20C188013F5", "name": iPhone 8 Plus, "os": com.apple.CoreSimulator.SimRuntime.iOS-15-4 }: [auto-ios-aarch64-sim, auto-ios-x86_64]
```
Though, on non-m1 apple products it will still display `auto-ios-aarch64-sim` and if ran, I assume it would fail with a weird error but I've not tested that. Should I make non aarch64 devices not …
=> Initial stuff for aarch64 ios simulator support

Cargo.lock, cargo-dinghy/src/main.rs, dinghy-lib/Cargo.toml, dinghy-lib/src/android/device.rs, dinghy-lib/src/android/mod.rs, dinghy-lib/src/host/platform.rs, dinghy-lib/src/ios/device.rs, dinghy-lib/src/platform/mod.rs, dinghy-lib/src/script/device.rs, dinghy-lib/src/ssh/device.rs, dinghy-lib/src/utils.rs
This builds upon #167 and ~doesn't cover ios as #168 is not merged yet~ UPDATED with ios support
This changes  how logs are handled in dinghy and add the new concept of "user facing logs", that are now controled by the `-v` arguments on the commandline.
Regular rust logging is still available via env logger using the `DINGHY_LOG` environment variable. (Still usefull when debugging dinghy, not so much for regular users)
The idea is to emulate the way cargo works and have a coherent experience for the user.
Here is a sample result without passing any verbose flag
```
cargo dinghy -d android  run
Targeting platform android-aarch64-ndk16b and device 'e3cca7b9'
Compiling hello v0.1.0 (/tmp/hello)
Finished dev [unoptimized + debuginfo] target(s) in 0.48s
Running …
```
=> Logging overhaul

dinghy-lib/src/ios/xcode.rs
I accidentally put a newer `openssl` first in my PATH, and encountered this
=> Support newer versions of the OpenSSL x509 text format

docs/ios.md
Since #168 ios-deploy is needed, thus this should be mentioned in the docu.
=> Mention ios-deploy in docu

dinghy-lib/src/android/device.rs, dinghy-lib/src/ssh/device.rs
Sometimes you want to be able to run with `--env RUST_BACKTRACE=full` and this is not possible with `dinghy` (which sets it to `1`). This patch makes RUST_BACKTRACE overwritable by `--env`.
=> make RUST_BACKTRACE overwritable by --env

.github/workflows/binaries.yml
Closes #200.
Similar work to [`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall/pull/551/files).
=> Universal macos binary in CI

.github/workflows/test.yml, .travis.sh
[Github now has m1 runners](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/). Using macOS-14 will exclusively run on M1s while macOS-13 will still be on intel.
=> Test on macOS-13 (x86) and macOS-14 (arm)

dinghy-lib/src/android/mod.rs
According the Path::join's docs, if `path` is absolute, it replaces the
current path, which clearly wasn't the intention in the existing code.
=> android: fix SDK detection on mac.

README.md, cargo-dinghy/src/main.rs
=> Infer the platform when runner is called in standalone mode

.github/workflows/test.yml, .travis.sh, README.md
Ran into this issue in #223 but felt it should go in it's own PR.
~In https://github.com/rust-lang/cargo/pull/13324, msrv was bumped to 1.73 (MSRV=N-2) and someplace down the line a patch release to `cargo-platform` was published. CI is pulling in `cargo-platform` for `0.1.8` which has msrv of 1.73.~
Clap and clap_derive were bumped to msrv 1.74 https://github.com/clap-rs/clap/pull/5343
There's an automated bot that updates the MSRV on cargo and cargo's subcrates so https://github.com/rust-lang/cargo/pull/13577 will cause breakages in the future.
After having changed this from 1.73 to 1.74, I feel like there should be a way to automate this similar to https://github.com/rust-lang/cargo/pull/13577. Though, I wish those bumps weren't considered patch releases :/
=> Bump msrv to 1.74

.github/workflows/test.yml, .travis.apple-third-tier.sh, .travis.sh
Over in https://github.com/sonos/dinghy/pull/223#discussion_r1558279214, it was suggested to move some of the apple simulator targets to be in a github action matrix.
=> Use matrix in CI for third tier apple simulators

cargo-dinghy/src/main.rs, dinghy-lib/src/apple/xcode.rs, dinghy-lib/src/config.rs, dinghy-lib/src/device.rs, dinghy-lib/src/lib.rs
Dinghy copies all sources to the target device by default, while this this really useful in some cases, this can take some time and some precious space on some small device/huge project combinations.
This adds a `skip_source_copy` flag to the config that will disable this behaviour. The default behaviour stays the same, meaning this should not have any impact on existing setups
=> add `skip_source_copy` flag

.travis.apple-third-tier.sh
This reverts commit 3244bc9b01410a9c090240c75db2ae51fb13f1b6.
This can be reenabled as https://github.com/rust-lang/cargo/issues/14735 was fixed via https://github.com/rust-lang/cargo/pull/14850
The first run of this may fail as the new nightly is probably not there yet
=> Revert "Disable proc macro tests for tvOS and watchOS"

test-ws/Cargo.toml, test-ws/test-app/Cargo.toml, test-ws/test-proc-macro/Cargo.toml
I also bumped the edition of all the crates in the test workspace to 2021
=> fix workspace resolver warning in test-ws

dinghy-lib/src/android/mod.rs
for some reason we didn't search the default install location of the ndk in linux, this fixes it
=> search ndk in default install location in linux

dinghy-lib/src/android/platform.rs
the `all-devices` commands expects the debug output for the platforms to be short, and all other platforms just output the platform id here
the default debug impl is quite verbose for the android platform, that combined with the fact that android devices are compatible with multiple platforms made the output of `cargo dinghy all-devices` pretty much unusable if you had an android device connected.
=> Fix display of android platforms in cargo dinghy all-devices
